name: cal_service
dependencies:
  - python=3.6
  - pip
  - gunicorn
  - pip:
    - Flask==0.12.2
    - simplejson==3.11.1
    - requests==2.22.0
    - python-crontab==2.2.6
    - pytz==2017.3
    - flask-cors==3.0.3
    - flask-restful==0.3.9